// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eTPL.API.Data;

#nullable disable

namespace eTPL.API.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    [Migration("20260401103843_AddAuctionSystemFinal")]
    partial class AddAuctionSystemFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBidLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("BidAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_auction_bid_log", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBoard", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int");

                    b.Property<string>("DbStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FinalEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HighestBidderId")
                        .HasColumnType("int");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NormalEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AuctionId");

                    b.HasIndex("HighestBidderId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tbs_auction_board", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionGradeQuota", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAllowedPerUser")
                        .HasColumnType("int");

                    b.Property<int>("MaxOVR")
                        .HasColumnType("int");

                    b.Property<int>("MinOVR")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("tbs_auction_grade_quota", "dbo");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "S",
                            MaxAllowedPerUser = 1,
                            MaxOVR = 99,
                            MinOVR = 82
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "A",
                            MaxAllowedPerUser = 1,
                            MaxOVR = 81,
                            MinOVR = 81
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "B",
                            MaxAllowedPerUser = 4,
                            MaxOVR = 80,
                            MinOVR = 79
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "C",
                            MaxAllowedPerUser = 8,
                            MaxOVR = 78,
                            MinOVR = 77
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "D",
                            MaxAllowedPerUser = 8,
                            MaxOVR = 76,
                            MinOVR = 75
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "E",
                            MaxAllowedPerUser = 99,
                            MaxOVR = 74,
                            MinOVR = 65
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("setting_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<DateTime?>("AuctionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuctionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DailyBidEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DailyBidStartTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxSquadSize")
                        .HasColumnType("int");

                    b.Property<int>("MinBidPrice")
                        .HasColumnType("int");

                    b.Property<int>("StartingBudget")
                        .HasColumnType("int");

                    b.HasKey("SettingId");

                    b.ToTable("tbs_auction_settings", "dbo");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            DailyBidEndTime = new TimeSpan(0, 23, 59, 59, 0),
                            DailyBidStartTime = new TimeSpan(0, 8, 0, 0, 0),
                            MaxSquadSize = 23,
                            MinBidPrice = 60,
                            StartingBudget = 2000
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSquad", b =>
                {
                    b.Property<int>("SquadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("squad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SquadId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SquadId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId", "PlayerId")
                        .IsUnique();

                    b.ToTable("tbs_auction_squad", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionUserWallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wallet_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<int>("AvailableBalance")
                        .HasColumnType("int");

                    b.Property<int>("ReservedBalance")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tbs_auction_user_wallet", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.PesPlayerTeam", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_player");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlayer"));

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("player_name");

                    b.Property<int>("PlayerOvr")
                        .HasColumnType("int")
                        .HasColumnName("player_ovr");

                    b.HasKey("IdPlayer");

                    b.ToTable("pes_player_team", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("can_access");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_key");

                    b.Property<string>("MenuLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("menu_label");

                    b.Property<string>("UserLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_level");

                    b.HasKey("Id");

                    b.HasIndex("MenuKey", "UserLevel")
                        .IsUnique();

                    b.ToTable("tbm_permission", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LineId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("line_id");

                    b.Property<string>("LineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line_name");

                    b.Property<string>("LinePic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("line_pic");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("user_level");

                    b.HasKey("UserId");

                    b.ToTable("tbm_user", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBidLog", b =>
                {
                    b.HasOne("eTPL.API.Models.Auction.AuctionBoard", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBoard", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "HighestBidder")
                        .WithMany()
                        .HasForeignKey("HighestBidderId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eTPL.API.Models.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.Auction.PesPlayerTeam", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HighestBidder");

                    b.Navigation("Initiator");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSquad", b =>
                {
                    b.HasOne("eTPL.API.Models.Auction.PesPlayerTeam", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionUserWallet", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("eTPL.API.Models.Auction.AuctionUserWallet", "UserId")
                        .HasPrincipalKey("eTPL.API.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
