// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eTPL.API.Data;

#nullable disable

namespace eTPL.API.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    [Migration("20260517034904_AddClubLogoTable")]
    partial class AddClubLogoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBidLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AuctionId");

                    b.Property<int>("BidAmount")
                        .HasColumnType("int")
                        .HasColumnName("BidAmount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phase");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("LogId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_auction_bid_log", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBoard", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int")
                        .HasColumnName("CurrentPrice");

                    b.Property<string>("DbStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DbStatus");

                    b.Property<DateTime>("FinalEndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinalEndTime");

                    b.Property<int?>("HighestBidderId")
                        .HasColumnType("int")
                        .HasColumnName("HighestBidderId");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("InitiatorUserId");

                    b.Property<DateTime>("NormalEndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("NormalEndTime");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("AuctionId");

                    b.HasIndex("HighestBidderId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("PlayerId");

                    b.ToTable("tbs_auction_board", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionGradeQuota", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GradeName");

                    b.Property<int>("MaxAllowedPerUser")
                        .HasColumnType("int")
                        .HasColumnName("MaxAllowedPerUser");

                    b.Property<int>("MaxOVR")
                        .HasColumnType("int")
                        .HasColumnName("MaxOVR");

                    b.Property<int>("MaxSeasonsPerTeam")
                        .HasColumnType("int")
                        .HasColumnName("MaxSeasonsPerTeam")
                        .HasAnnotation("Relational:JsonPropertyName", "maxSeasonsPerTeam");

                    b.Property<int>("MinOVR")
                        .HasColumnType("int")
                        .HasColumnName("MinOVR");

                    b.Property<int>("ReleasePercent")
                        .HasColumnType("int")
                        .HasColumnName("ReleasePercent")
                        .HasAnnotation("Relational:JsonPropertyName", "releasePercent");

                    b.Property<int>("RenewalPercent")
                        .HasColumnType("int")
                        .HasColumnName("RenewalPercent")
                        .HasAnnotation("Relational:JsonPropertyName", "renewalPercent");

                    b.HasKey("GradeId");

                    b.ToTable("tbs_auction_grade_quota", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("setting_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<DateTime?>("AuctionEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AuctionEndDate");

                    b.Property<DateTime?>("AuctionStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AuctionStartDate");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("int")
                        .HasColumnName("CurrentSeason");

                    b.Property<TimeSpan>("DailyBidEndTime")
                        .HasColumnType("time")
                        .HasColumnName("DailyBidEndTime");

                    b.Property<TimeSpan>("DailyBidStartTime")
                        .HasColumnType("time")
                        .HasColumnName("DailyBidStartTime");

                    b.Property<int>("FinalBidDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("FinalBidDurationMinutes");

                    b.Property<int>("MaxSquadSize")
                        .HasColumnType("int")
                        .HasColumnName("MaxSquadSize");

                    b.Property<int>("MinBidPrice")
                        .HasColumnType("int")
                        .HasColumnName("MinBidPrice");

                    b.Property<int>("NormalBidDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("NormalBidDurationMinutes");

                    b.Property<int>("StartingBudget")
                        .HasColumnType("int")
                        .HasColumnName("StartingBudget");

                    b.HasKey("SettingId");

                    b.ToTable("tbs_auction_settings", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSquad", b =>
                {
                    b.Property<int>("SquadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("squad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SquadId"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("AcquiredAt");

                    b.Property<bool>("IsLoan")
                        .HasColumnType("bit")
                        .HasColumnName("IsLoan");

                    b.Property<int?>("ListingPrice")
                        .HasColumnType("int")
                        .HasColumnName("ListingPrice");

                    b.Property<DateTime?>("LoanExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("LoanExpiry");

                    b.Property<int?>("LoanedFromUserId")
                        .HasColumnType("int")
                        .HasColumnName("LoanedFromUserId");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerId");

                    b.Property<int>("PricePaid")
                        .HasColumnType("int")
                        .HasColumnName("PricePaid");

                    b.Property<int>("SeasonsWithTeam")
                        .HasColumnType("int")
                        .HasColumnName("SeasonsWithTeam");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("SquadId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_auction_squad", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("BalanceAfter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direction");

                    b.Property<int?>("RelatedAuctionId")
                        .HasColumnType("int")
                        .HasColumnName("RelatedAuctionId");

                    b.Property<int?>("RelatedPlayerId")
                        .HasColumnType("int")
                        .HasColumnName("RelatedPlayerId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_auction_transactions", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionUserWallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wallet_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<int>("AvailableBalance")
                        .HasColumnType("int")
                        .HasColumnName("AvailableBalance");

                    b.Property<int>("ReservedBalance")
                        .HasColumnType("int")
                        .HasColumnName("ReservedBalance");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tbs_auction_user_wallet", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.PesPlayerTeam", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_player");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlayer"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Foot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foot");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("IdTeam")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_team");

                    b.Property<string>("League")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("league");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("player_name");

                    b.Property<int>("PlayerOvr")
                        .HasColumnType("int")
                        .HasColumnName("player_ovr");

                    b.Property<string>("PlayingStyle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("playing_style");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("team_name");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("IdPlayer");

                    b.ToTable("pes_player_team", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.SpecialBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ApprovedAt");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApprovedBy");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_special_bonus", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.TransferOffer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("offer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("FromUserId");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfferType");

                    b.Property<int>("SquadId")
                        .HasColumnType("int")
                        .HasColumnName("SquadId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("ToUserId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("OfferId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("SquadId");

                    b.HasIndex("ToUserId");

                    b.ToTable("tbs_transfer_offer", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.ClubLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("file_name");

                    b.Property<string>("LogoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("logo_name");

                    b.HasKey("Id");

                    b.ToTable("tbs_club_logo", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.CupFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("away_score");

                    b.Property<string>("AwayUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("away_user_id");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("home_score");

                    b.Property<string>("HomeUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("home_user_id");

                    b.Property<bool>("IsBye")
                        .HasColumnType("bit")
                        .HasColumnName("is_bye");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("bit")
                        .HasColumnName("is_played");

                    b.Property<int>("MatchNo")
                        .HasColumnType("int")
                        .HasColumnName("match_no");

                    b.Property<Guid?>("NextMatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("next_match_id");

                    b.Property<int>("Round")
                        .HasColumnType("int")
                        .HasColumnName("round");

                    b.Property<int>("Season")
                        .HasColumnType("int")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.ToTable("tbs_cup_fixture", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.LeagueOps.DailyCheckin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("checkin_date");

                    b.Property<int>("CycleId")
                        .HasColumnType("int")
                        .HasColumnName("cycle_id");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit")
                        .HasColumnName("is_ready");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("tbs_daily_checkins", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.LeagueOps.JudgeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_id");

                    b.Property<string>("ConfigSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_snapshot");

                    b.Property<int>("CycleId")
                        .HasColumnType("int")
                        .HasColumnName("cycle_id");

                    b.Property<DateTime>("JudgeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("judge_date");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int")
                        .HasColumnName("match_count");

                    b.HasKey("Id");

                    b.ToTable("tbs_judge_history", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.LeagueOps.LeagueCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusPool")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("bonus_pool");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cycle_name");

                    b.Property<int>("EiThreshold")
                        .HasColumnType("int")
                        .HasColumnName("ei_threshold");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<int>("MatchEndNo")
                        .HasColumnType("int")
                        .HasColumnName("match_end_no");

                    b.Property<int>("MatchStartNo")
                        .HasColumnType("int")
                        .HasColumnName("match_start_no");

                    b.Property<int>("MatchTarget")
                        .HasColumnType("int")
                        .HasColumnName("match_target");

                    b.Property<int>("RateActive")
                        .HasColumnType("int")
                        .HasColumnName("rate_active");

                    b.Property<int>("RateElite")
                        .HasColumnType("int")
                        .HasColumnName("rate_elite");

                    b.Property<int>("RateInactive")
                        .HasColumnType("int")
                        .HasColumnName("rate_inactive");

                    b.Property<int>("RateWarning")
                        .HasColumnType("int")
                        .HasColumnName("rate_warning");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tbs_league_cycles", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.LeagueOps.LeagueOpsStatResult", b =>
                {
                    b.Property<decimal?>("ei_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("est_bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("multiplier")
                        .HasColumnType("int");

                    b.Property<decimal?>("p_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("played_count")
                        .HasColumnType("int");

                    b.Property<decimal?>("r_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ready_days")
                        .HasColumnType("int");

                    b.Property<string>("tier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LeagueOpsStatResults", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TargetUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbs_notifications", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("TargetPlatform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("target_platform");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("template_text");

                    b.HasKey("Id");

                    b.ToTable("tbs_notification_template", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("can_access");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_key");

                    b.Property<string>("MenuLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("menu_label");

                    b.Property<string>("UserLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_level");

                    b.HasKey("Id");

                    b.HasIndex("MenuKey", "UserLevel")
                        .IsUnique();

                    b.ToTable("tbm_permission", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.QaInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("tbm_qa_information", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.ApiVFixtureAll", b =>
                {
                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<string>("AwayImage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("AWAY_IMAGE");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<string>("AwayTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY_TEAM_NAME");

                    b.Property<int?>("AwayUserId")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_USER_ID");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("FixtureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<string>("HomeImage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("HOME_IMAGE");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<string>("HomeTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME_TEAM_NAME");

                    b.Property<int?>("HomeUserId")
                        .HasColumnType("int")
                        .HasColumnName("HOME_USER_ID");

                    b.Property<string>("IsPlayed")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("IS_PLAYED");

                    b.Property<int?>("Leg")
                        .HasColumnType("int")
                        .HasColumnName("LEG");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATCH_DATE");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.ToTable((string)null);

                    b.ToView("api_v_fixture_all", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.ApiVResultTable", b =>
                {
                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<string>("Image")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("L")
                        .HasColumnType("int");

                    b.Property<string>("Last")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Pl")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int>("Pos")
                        .HasColumnType("int")
                        .HasColumnName("POS");

                    b.Property<int?>("Pts")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("api_v_result_table", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.BotMessage", b =>
                {
                    b.Property<int>("MsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("msg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MsgId"));

                    b.Property<string>("InputMsg")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("input_msg");

                    b.Property<string>("ResponseMsg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_msg");

                    b.HasKey("MsgId");

                    b.ToTable("bot_message", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.InsertUser", b =>
                {
                    b.Property<string>("Expr1")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Expr2")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Expr3")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("Expr4")
                        .HasColumnType("int");

                    b.Property<string>("Player")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PLAYER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID");

                    b.ToTable((string)null);

                    b.ToView("insert_user", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TblFixtureLog", b =>
                {
                    b.Property<string>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<int?>("AwayRed")
                        .HasColumnType("int")
                        .HasColumnName("away_red");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<int?>("AwayYellow")
                        .HasColumnType("int")
                        .HasColumnName("away_yellow");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<int?>("HomeRed")
                        .HasColumnType("int")
                        .HasColumnName("home_red");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<int?>("HomeYellow")
                        .HasColumnType("int")
                        .HasColumnName("home_yellow");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATCH_DATE");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.HasKey("FixtureId");

                    b.ToTable("tbl_fixture_log", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TblLeave", b =>
                {
                    b.Property<Guid>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("leave_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DateFrom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DATE_FROM");

                    b.Property<string>("DateTo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DATE_TO");

                    b.Property<string>("Platform")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("PLATFORM");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REASON");

                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("USER_ID")
                        .IsFixedLength();

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("LeaveId");

                    b.ToTable("tbl_leave", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmAnnouce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Announcement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("announcement");

                    b.Property<string>("Announcer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("announcer");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSharedFacebook")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("platform");

                    b.HasKey("Id");

                    b.ToTable("tbm_annouce", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmCurrentSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Platform")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("platform");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.ToTable("tbm_current_season", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmFinalResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<string>("Image")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("L")
                        .HasColumnType("int");

                    b.Property<int?>("Pl")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PLATFORM");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("POSITION");

                    b.Property<int?>("Pts")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TEAM");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbm_final_result", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmFixtureAll", b =>
                {
                    b.Property<string>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<int?>("AwayRed")
                        .HasColumnType("int")
                        .HasColumnName("away_red");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<int?>("AwayYellow")
                        .HasColumnType("int")
                        .HasColumnName("away_yellow");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<int?>("HomeRed")
                        .HasColumnType("int")
                        .HasColumnName("home_red");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<int?>("HomeYellow")
                        .HasColumnType("int")
                        .HasColumnName("home_yellow");

                    b.Property<int?>("Leg")
                        .HasColumnType("int")
                        .HasColumnName("LEG");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATCH_DATE");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.HasKey("FixtureId");

                    b.ToTable("tbm_fixture_all", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmHof", b =>
                {
                    b.Property<string>("HofId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hof_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AiImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AiPrompt")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RunnerUpName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TournamentSubtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TournamentTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WinnerImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WinnerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WinnerTeam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("HofId");

                    b.ToTable("tbs_hof", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmNewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Facebook")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("facebook");

                    b.Property<string>("MemberId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("member_id");

                    b.Property<string>("MemberImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("member_image");

                    b.Property<string>("MemberName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("member_name");

                    b.Property<string>("Platform")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("platform");

                    b.HasKey("Id");

                    b.ToTable("tbm_new_member", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmSystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SettingKey");

                    b.ToTable("tbm_system_setting", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbmTeam", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Md5TeamId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MD5_TEAM_ID");

                    b.Property<int?>("Overall")
                        .HasColumnType("int")
                        .HasColumnName("OVERALL");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<string>("Player")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PLAYER");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("tbm_team", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbsPrizeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("AMOUNT");

                    b.Property<int?>("PositionEnd")
                        .HasColumnType("int")
                        .HasColumnName("POSITION_END");

                    b.Property<int?>("PositionStart")
                        .HasColumnType("int")
                        .HasColumnName("POSITION_START");

                    b.Property<string>("RankLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RANK_LABEL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SORT_ORDER");

                    b.HasKey("Id");

                    b.ToTable("tbs_prize_setting", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.TbtResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("D")
                        .HasColumnType("int")
                        .HasColumnName("D");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("FixtureId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<int?>("L")
                        .HasColumnType("int")
                        .HasColumnName("L");

                    b.Property<int?>("Pl")
                        .HasColumnType("int")
                        .HasColumnName("PL");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Pts")
                        .HasColumnType("int")
                        .HasColumnName("PTS");

                    b.Property<int?>("Red")
                        .HasColumnType("int")
                        .HasColumnName("red");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM");

                    b.Property<int?>("W")
                        .HasColumnType("int")
                        .HasColumnName("W");

                    b.Property<int?>("Yellow")
                        .HasColumnType("int")
                        .HasColumnName("yellow");

                    b.HasKey("Id");

                    b.ToTable("tbt_result", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VCurrentTeam", b =>
                {
                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Md5TeamId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MD5_TEAM_ID");

                    b.Property<int?>("Overall")
                        .HasColumnType("int")
                        .HasColumnName("OVERALL");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<string>("Player")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PLAYER");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.ToTable((string)null);

                    b.ToView("v_current_team", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VFixture", b =>
                {
                    b.Property<string>("AImage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("A_IMAGE");

                    b.Property<string>("AName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("A_NAME");

                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("FixtureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id");

                    b.Property<string>("HImage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("H_IMAGE");

                    b.Property<string>("Hname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HNAME");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.ToTable((string)null);

                    b.ToView("v_fixture", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VFixtureAll", b =>
                {
                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<string>("AwayImage")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("AWAY_IMAGE");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<string>("AwayTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY_TEAM_NAME");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("FixtureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<string>("HomeImage")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("HOME_IMAGE");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<string>("HomeTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME_TEAM_NAME");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.ToTable((string)null);

                    b.ToView("v_fixture_all", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VFixtureAllLog", b =>
                {
                    b.Property<string>("Active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<string>("AwayImage")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("AWAY_IMAGE");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<string>("AwayTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY_TEAM_NAME");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("FixtureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<string>("HomeImage")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("HOME_IMAGE");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<string>("HomeTeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME_TEAM_NAME");

                    b.Property<int?>("Match")
                        .HasColumnType("int")
                        .HasColumnName("MATCH");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATCH_DATE");

                    b.Property<string>("MatchDateDisplay")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MATCH_DATE_DISPLAY");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<string>("ResultImage")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("RESULT_IMAGE");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.ToTable((string)null);

                    b.ToView("v_fixture_all_log", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VHof", b =>
                {
                    b.Property<string>("D1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("D1Image")
                        .HasMaxLength(272)
                        .HasColumnType("nvarchar(272)")
                        .HasColumnName("D1_IMAGE");

                    b.Property<string>("D2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("D2Image")
                        .HasMaxLength(272)
                        .HasColumnType("nvarchar(272)")
                        .HasColumnName("D2_IMAGE");

                    b.Property<string>("FaCup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FA CUP");

                    b.Property<string>("FaImage")
                        .HasMaxLength(272)
                        .HasColumnType("nvarchar(272)")
                        .HasColumnName("FA_IMAGE");

                    b.Property<string>("HofId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hof_id");

                    b.Property<string>("LcImage")
                        .HasMaxLength(272)
                        .HasColumnType("nvarchar(272)")
                        .HasColumnName("LC_IMAGE");

                    b.Property<string>("LeagueCup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LEAGUE CUP");

                    b.Property<string>("Platform")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PLATFORM");

                    b.Property<double?>("Season")
                        .HasColumnType("float")
                        .HasColumnName("SEASON");

                    b.Property<string>("SeasonImage")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)")
                        .HasColumnName("SEASON_IMAGE");

                    b.Property<string>("ThImage")
                        .HasMaxLength(272)
                        .HasColumnType("nvarchar(272)")
                        .HasColumnName("TH_IMAGE");

                    b.Property<string>("ThaiClubCup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("THAI CLUB CUP");

                    b.ToTable((string)null);

                    b.ToView("v_hof", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VLastFixture", b =>
                {
                    b.Property<int?>("AUserId")
                        .HasColumnType("int")
                        .HasColumnName("A_USER_ID");

                    b.Property<string>("Away")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AWAY");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("AWAY_SCORE");

                    b.Property<int?>("HUserId")
                        .HasColumnType("int")
                        .HasColumnName("H_USER_ID");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOME");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("HOME_SCORE");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("MATCH_DATE");

                    b.ToTable((string)null);

                    b.ToView("v_last_fixture", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VPlayerDraw", b =>
                {
                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIVISION");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Player")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PLAYER");

                    b.ToTable((string)null);

                    b.ToView("v_player_draw", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VResultTable", b =>
                {
                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Image")
                        .HasMaxLength(71)
                        .HasColumnType("nvarchar(71)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("L")
                        .HasColumnType("int");

                    b.Property<int?>("Pl")
                        .HasColumnType("int");

                    b.Property<int?>("Pts")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(103)
                        .HasColumnType("nvarchar(103)")
                        .HasColumnName("TEAM");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_result_table", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VResultTableCalculate", b =>
                {
                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Image")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("L")
                        .HasColumnType("int");

                    b.Property<string>("Last")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Pl")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Pts")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_result_table_calculate", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.Scaffolded.VResultTableNew", b =>
                {
                    b.Property<int?>("D")
                        .HasColumnType("int");

                    b.Property<string>("Division")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DIVISION");

                    b.Property<int?>("Ga")
                        .HasColumnType("int")
                        .HasColumnName("GA");

                    b.Property<int?>("Gd")
                        .HasColumnType("int")
                        .HasColumnName("GD");

                    b.Property<int?>("Gf")
                        .HasColumnType("int")
                        .HasColumnName("GF");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Image")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)")
                        .HasColumnName("IMAGE");

                    b.Property<int?>("L")
                        .HasColumnType("int");

                    b.Property<string>("Last")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Pl")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLATFORM");

                    b.Property<int?>("Pts")
                        .HasColumnType("int");

                    b.Property<int?>("Season")
                        .HasColumnType("int")
                        .HasColumnName("SEASON");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM");

                    b.Property<string>("TeamName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEAM_NAME");

                    b.Property<int?>("W")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_result_table_new", "dbo");
                });

            modelBuilder.Entity("eTPL.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentTeam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("current_team");

                    b.Property<string>("LineId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("line_id");

                    b.Property<string>("LineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line_name");

                    b.Property<string>("LinePic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("line_pic");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("TeamNickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("team_nickname");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("user_level");

                    b.HasKey("Id");

                    b.ToTable("tbm_user", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBidLog", b =>
                {
                    b.HasOne("eTPL.API.Models.Auction.AuctionBoard", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionBoard", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "HighestBidder")
                        .WithMany()
                        .HasForeignKey("HighestBidderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eTPL.API.Models.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.Auction.PesPlayerTeam", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HighestBidder");

                    b.Navigation("Initiator");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionSquad", b =>
                {
                    b.HasOne("eTPL.API.Models.Auction.PesPlayerTeam", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionTransaction", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.AuctionUserWallet", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("eTPL.API.Models.Auction.AuctionUserWallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.SpecialBonus", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eTPL.API.Models.Auction.TransferOffer", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.Auction.AuctionSquad", "Squad")
                        .WithMany()
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eTPL.API.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Squad");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("eTPL.API.Models.Notification", b =>
                {
                    b.HasOne("eTPL.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
